### PR TITLE
Modernize max players in MapPersistentContext

### PR DESCRIPTION
**Pull request by TheMolkaPL**
image

Finally resolves Electroid/PGM#154

### CODE REVIEW

**Comment by Pablete1234** [comment]
Well this will already have a 20 vs 20 vs 20 as the format for 3+team maps. Using a 3-team map was just an example. The "normal" behaviour it will see is usually going to be `50 (25 vs 25)`, but i think it makes sense to keep both the sum and the split amounts.

**Comment by Electroid** [comment]
On second thought.. what if we did something like this?

```
// When all team sizes are the same
2 teams of 50 players
3 teams of 20 players
// When there are different size teams
1 team of 10 players, 2 teams of 20 players
```

**Comment by Pablete1234** [comment]
I think such format just gets needlessly verbose, probably best to keep it somewhat short

**Comment by Electroid** [comment]
When the team sizes are even, it's not verbose?

**Comment by Pablete1234** [comment]
`2 teams of 20 players` is still longer than `40 (20 vs 20)`, without including the total

Only for maps where there's many teams (probably 4+) it may take up less space

**Comment by TheMolkaPL** [comment]
image

**Pull request merged**
