### PR TITLE
Drops inventory on disconnect if player is in a match.

### PR DESCRIPTION
**Pull request by KingOfSquares**
Signed-off-by: KingOfSquares <simonmorland@gmail.com>

Yeah i broke #327 but this is the same lol

@BGMP wops 😮

### CODE REVIEW

**Comment by BGMP** [comment]
:facedesk:

**Comment by Electroid** [comment]
@KingOfSquares You can `git push --force` to your current PR branch to make changes.

Also please make the commit relevant :)

**Comment by Electroid** [comment]
1. Make sure you are on your branch.
2. `git reset HEAD^`
3. `git add --all`
4. `git commit -s -m "Your message"
5. `git push --force`

**Comment by KingOfSquares** [comment]
Yes sorry Electroid, i did it wrong again.. :(

**Comment by Electroid** [comment]
It's okay! Feel free to ask here or in Discord if you have any issues! 🚀

**Pull request merged**
