### PR TITLE
Don't suggest setting key aliases

### PR DESCRIPTION
**Pull request by TheMolkaPL**
Currently, after typing `/toggle ` it suggests all available aliases, which is confusing, as it looks like there are more settings.

### CODE REVIEW

**Comment by Pablete1234** [comment]
Instead of suggesting only the main name, consider suggesting the first available alias for each setting

**Comment by TheMolkaPL** [comment]
First alias is always the main name.

https://github.com/Electroid/PGM/blob/1a604f129d510489aa9ec0a398a31b3c787c139d/src/main/java/tc/oc/pgm/api/setting/SettingKey.java#L35-L42

**Comment by Pablete1234** [comment]
@TheMolkaPL what i mean is the first alias that matches your search.

Example: "death" or "dms":
`/toggle d` it should autocomplete "death", and no more aliases of that setting
`/toggle dm` it should autocomplete "dms", and no more aliases of that setting

**Comment by Electroid** [comment]
@TheMolkaPL Is something wrong with this PR? You only seem to have changed the java doc?

**Comment by Pablete1234** [comment]
@Electroid the java-doc and the added `break;`, wich is all needed for this fix

**Pull request merged**
