### PR TITLE
Remove edit wand

### PR DESCRIPTION
**Pull request by TheMolkaPL**
It seems that edit wand isn't used anywhere.

### CODE REVIEW

**Comment by Electroid** [comment]
It's used for WorldEdit for moderators.

**Comment by TheMolkaPL** [comment]
Should be somehow configurable then.

**Comment by Brottweiler** [comment]
@TheMolkaPL it is, in the worldedit config.

**Comment by TheMolkaPL** [comment]
I don't even have WorldEdit. Teleportation tool and edit wand (or any other item you want) should be imo configurable in PGM.

**Comment by Brottweiler** [comment]
There's no reason not to have WorldEdit though; the compass is useful for any player.

**Comment by Electroid** [comment]
@TheMolkaPL To remove the wand, you can add a negative permission for the wand.

**Pull request closed without merging**
