### PR TITLE
Added a changelog

### PR DESCRIPTION
**Pull request by rafibaum**
Now that PGM is a public plugin seeking to make a release to the wider Minecraft community, it's important we start implementing a release system. A changelog is part of that and I've written up one for the next release with all the changes since 0.7. Contributors will be expected to update this document as part of their PR with their changes.

### CODE REVIEW

**Comment by EricZeiberg** [comment]
I would sort the feature list, so all new commands, then new XML modules, etc...

**Comment by rafibaum** [comment]
Good idea, I'll do that.

**Comment by KingOfSquares** [comment]
Don't think users will care about refactors?

**Comment by Electroid** [comment]
I think we should keep this very user centric. New commands, new xml features. In terms of refactors, if we do our job right, we shouldn't need to keep track of it :)

**Comment by Pablete1234** [comment]
Refactors should be mentioned when they mean something to the user. Refactored X to support X and X new features, is something that you can mention, but saying that you refactored some part of the code without any user-facing counterpart isn't needed

**Comment by Electroid** [comment]
This is now on the release notes.

**Pull request closed without merging**
