### PR TITLE
Change visibility of PlayerOrder constructor and add getter for viewer field

### PR DESCRIPTION
**Pull request by Meeples10**
Signed-off-by: Meeples10 <mc.meeples10@gmail.com>

### CODE REVIEW

**Comment by EricZeiberg** [comment]
What's the reasoning for this change?

**Comment by KingOfSquares** [comment]
Im guessing it's for rendering the tablist based on who is watching?

**Comment by Meeples10** [comment]
>What's the reasoning for this change?

@EricZeiberg External plugins can't extend `PlayerOrder` without a public constructor and a getter for the viewer.

**Comment by Electroid** [comment]
This is now on master. Be cautious though, PGM doesn't have an official API, this might break in the future.

**Pull request closed without merging**
